# Generated by Django 4.1.6 on 2023-02-04 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=20)),
                ("balance", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True, verbose_name="삭제 여부")),
                ("deleted_at", models.DateTimeField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "account_books",
            },
        ),
        migrations.CreateModel(
            name="AccountBookRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField(verbose_name="금액")),
                ("description", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("is_active", models.BooleanField(default=True, verbose_name="삭제 여부")),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "account_book",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account_book.accountbook"),
                ),
            ],
            options={
                "db_table": "account_book_records",
            },
        ),
    ]
